// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbnxyLMvZ43VxizfDa-qs-aWgY7YQDBE',
    appId: '1:300828025223:web:ada501df854e303775b322',
    messagingSenderId: '300828025223',
    projectId: 'focusyn-app',
    authDomain: 'focusyn-app.firebaseapp.com',
    storageBucket: 'focusyn-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZz3x6mywSc5cP4VArj7Zvpi2UoEdyCZg',
    appId: '1:300828025223:android:3196bb2f9b35773875b322',
    messagingSenderId: '300828025223',
    projectId: 'focusyn-app',
    storageBucket: 'focusyn-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADX7H2ivb5jvS6-v_UnH9DHoorgq_t32s',
    appId: '1:300828025223:ios:ebf942c88489150a75b322',
    messagingSenderId: '300828025223',
    projectId: 'focusyn-app',
    storageBucket: 'focusyn-app.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADX7H2ivb5jvS6-v_UnH9DHoorgq_t32s',
    appId: '1:300828025223:ios:ebf942c88489150a75b322',
    messagingSenderId: '300828025223',
    projectId: 'focusyn-app',
    storageBucket: 'focusyn-app.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbnxyLMvZ43VxizfDa-qs-aWgY7YQDBE',
    appId: '1:300828025223:web:2b96a153c500255475b322',
    messagingSenderId: '300828025223',
    projectId: 'focusyn-app',
    authDomain: 'focusyn-app.firebaseapp.com',
    storageBucket: 'focusyn-app.firebasestorage.app',
  );
}
